# Lighting automations.
# Includes intent-based control via Alice IR scenes.
automation:
  - id: request_turn_off_ceiling_light_when_away
    alias: "Request ceiling light OFF when Andrey away"
    mode: single
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.andrey_home_final
          - input_boolean.ceiling_light_intent
    condition:
      - condition: state
        entity_id: binary_sensor.andrey_home_final
        state: "off"   # Andrey away
      - condition: state
        entity_id: input_boolean.ceiling_light_intent
        state: "on"    # Light intent is ON
    action:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.ceiling_light_turn_off_request